import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createWorkerBackend, runBoundedProcess } from '../server/worker.ts';
import { analyzeEditorContext } from '../server/editor-context.ts';
import type { Analysis } from '../src/core/types.ts';
import { inspectSmallDefinitions } from '../src/semantic/inspection.ts';
import { compileSemanticDocument } from '../src/semantic/compiler.ts';
import { compileReading } from '../src/reading/index.ts';
const rootDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const backend=createWorkerBackend({rootDir});
const temporary=await mkdtemp(path.join(os.tmpdir(),'statementlens-preview-test-'));
const config=JSON.parse(await readFile(path.join(rootDir,'.local/config.json'),'utf8'));
let checks=0;
const flatten=(node:any):any[]=>[node,...node.children.flatMap(flatten)];
try {
  const source='∀ (X Y : Type) (f : X → Y), Function.Injective f';
  const normal:any=await backend.analyze(source);
  const offered:any=await backend.analyze(source,undefined,{previewDefinitions:true});
  assert.equal(offered.ok,true,JSON.stringify(offered));assert.deepEqual(offered.tree,normal.tree);
  assert.equal(offered.source,source);assert.equal(offered.pretty,normal.pretty);
  const preview=offered.definitionPreviews.find((p:any)=>p.constant==='Function.Injective');
  assert.ok(preview);assert.equal(preview.originalPretty,normal.pretty);
  assert.ok(flatten(preview.tree).some(node=>node.expansion?.constant==='Function.Injective'));
  assert.ok(flatten(preview.tree).length>flatten(offered.tree).length);
  assert.deepEqual(preview.expansionPolicy,{constants:['Function.Injective'],maxDepth:1});checks++;
  assert.deepEqual(normal.definitionPreviews,[]);checks++;
  const manual:any=await backend.analyze(source,undefined,{previewDefinitions:true,expansion:{constants:['Function.Injective'],maxDepth:1}});
  assert.equal(manual.ok,true);assert.deepEqual(manual.definitionPreviews,[]);checks++;
  await writeFile(path.join(temporary,'lean-toolchain'),'leanprover/lean4:v4.28.0\n');
  const fileName=path.join(temporary,'Preview.lean');
  await writeFile(fileName,'-- Source buffer is supplied independently.\n');
  async function context(prefix:string,term:string){
    const buffer=prefix+'\n#check '+term+'\n',line=prefix.split('\n').length;
    const result:any=await analyzeEditorContext({engineDirectory:rootDir,fileName,source:buffer,workspaceTrusted:true,previewDefinitions:true,selection:{start:{line,character:7},end:{line,character:7+term.length}}});
    assert.equal(result.ok,true,JSON.stringify(result));return result;
  }
  const bad=await context('def Broken (n : Nat) : Prop := by sorry','∀ (n : Nat), Broken n');
  assert.deepEqual(bad.definitionPreviews,[]);checks++;
  const large=await context('def Large (n : Nat) : Prop := '+Array.from({length:100},()=> 'n = n').join(' ∧ '),'∀ (n : Nat), Large n');
  assert.deepEqual(large.definitionPreviews,[]);checks++;
  const four=await context([1,2,3,4].map(n=>`def P${n} (x : Nat) : Prop := x = x ∧ True`).join('\n'),'∀ (x : Nat), P1 x ∧ P2 x ∧ P3 x ∧ P4 x');
  assert.equal(four.definitionPreviews.length,3);
  assert.ok(Buffer.byteLength(JSON.stringify(four.definitionPreviews))<=262144);
  assert.deepEqual(new Set(four.definitionPreviews.map((p:any)=>p.constant)),new Set(['P1','P2','P3']));checks++;
  const hypothesisLines=['import Lean','def Wrapped (P : Prop) : Prop := P',
    'example (n : Nat) (h : Wrapped (n = n)) : n = n := by rfl'];
  const hypothesisSource=hypothesisLines.join('\n');
  const conclusionStart=hypothesisLines[2]!.lastIndexOf('n = n');
  const hypothesisResult=await analyzeEditorContext({engineDirectory:rootDir,fileName,source:hypothesisSource,workspaceTrusted:true,previewDefinitions:true,
    selection:{start:{line:2,character:conclusionStart},end:{line:2,character:conclusionStart+5}}});
  assert.equal(hypothesisResult.ok,true,JSON.stringify(hypothesisResult));
  const hypothesis=hypothesisResult as unknown as Analysis;
  assert.equal(hypothesis.definitions?.filter(definition=>definition.name==='Wrapped').length,1);
  assert.ok(hypothesis.definitions?.find(definition=>definition.name==='Wrapped')?.canExpand);
  assert.ok(hypothesis.definitionPreviews?.find(candidate=>candidate.constant==='Wrapped'));
  const inspected=inspectSmallDefinitions(hypothesis);
  assert.equal(inspected.automaticInspection?.constant,'Wrapped');
  assert.equal(inspected.source,hypothesisSource);
  const originalAssumption=flatten(hypothesis.tree).find(node=>node.binder?.name==='h');
  const assumption=flatten(inspected.tree).find(node=>node.binder?.name==='h');
  assert.equal(assumption.kind,'implies');assert.equal(assumption.binder.role,'assumption');
  assert.equal(assumption.binder.id,originalAssumption.binder.id);
  assert.equal(assumption.children[0].expansion?.constant,'Wrapped');
  assert.equal(assumption.children[1].lean,originalAssumption.children[1].lean);
  const document=compileSemanticDocument(inspected),reading=compileReading(document);
  const premise=reading.nodes.find(node=>node.id===assumption.children[0].id)!;
  const conclusion=reading.nodes.find(node=>node.id===assumption.children[1].id)!;
  assert.deepEqual(premise.assumptionNodeIds,[]);
  assert.deepEqual(conclusion.assumptionNodeIds,[premise.id]);
  const hypothesisObject=document.objects.find(object=>object.binder?.id===assumption.binder.id)!;
  assert.ok(!document.scopes.find(scope=>scope.nodeId===premise.id)!.objectIds.includes(hypothesisObject.id));
  assert.ok(document.scopes.find(scope=>scope.nodeId===conclusion.id)!.objectIds.includes(hypothesisObject.id));
  assert.equal(document.relations.filter(relation=>relation.kind==='equality').length,2);checks++;
  const boundsFile=path.join(temporary,'Bounds.lean');
  await writeFile(boundsFile,`import StatementLens.Response\nopen Lean\ndef main : IO Unit := do\n  let source := String.ofList (List.replicate 10000 'a')\n  let extra := String.ofList (List.replicate 20000 'b')\n  let original := Json.mkObj [("ok", toJson true), ("source", toJson source), ("definitionPreviews", Json.arr #[Json.mkObj [("constant", toJson "X"), ("tree", toJson extra)]])]\n  let result := StatementLens.Response.serializeResponse original 12000\n  unless result.utf8ByteSize <= 12000 do throw (IO.userError "optional preview broke the output cap")\n  let parsed ← IO.ofExcept (Json.parse result)\n  unless (parsed.getObjValAs? String "source").toOption == some source do throw (IO.userError "mandatory source was modified")\n  unless (parsed.getObjValAs? (Array Json) "definitionPreviews").toOption.getD #[] |>.isEmpty do throw (IO.userError "oversize preview was retained")\n  IO.println "preview bounds passed"\n`);
  const output=await runBoundedProcess(config.leanExecutable,{args:['--run',boundsFile],cwd:temporary,env:{...process.env,LEAN_PATH:config.leanPath.join(path.delimiter)},timeoutMs:10000});
  assert.match(output,/preview bounds passed/);checks++;
  console.log(`Definition previews: ${checks} native checks passed; caps, explicit policy, placeholders, and mandatory-response preservation verified.`);
} finally {backend.close?.();await rm(temporary,{recursive:true,force:true});}
